
import business.Customers;
import data.CustomerDB;
import business.SwingValidator;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class CustomerManagementSystem extends javax.swing.JFrame {

    /**
     * Creates new form CustomerManagementSystem
     */
    CustomerDB cDB = new CustomerDB();
    String mode = "";
    int oldID = 0;
    public CustomerManagementSystem() {
        initComponents();
        displayMode(true);
        showCustomer(cDB.getFirstCustomer());         
    }
    private void showCustomer(Customers c){
        String customerID = Integer.toString(c.getCustomerID());
        customerIDTextField.setText(customerID);
        customerNameTextField.setText(c.getCustomerName());
        dateOfJoinTextField.setText(c.getDateOfJoin());
        String revenue = Double.toString(c.getRevenue());
        revenueTextField.setText(revenue);
    }
    private void clearFields(){
        customerIDTextField.setText("");
        customerNameTextField.setText("");
        dateOfJoinTextField.setText("");
        revenueTextField.setText("");
    }
    private boolean isValidData(){
        SwingValidator sv = new SwingValidator();
        if(!sv.isPresent(this.customerIDTextField, "CustomerID"))
            return false;       
        if(!sv.isInterger(this.customerIDTextField , "CustomerID"))
            return false;
        if(!sv.isPresent(this.customerNameTextField , "CustomerName")) 
            return false;
        if(!sv.isPresent(this.dateOfJoinTextField , "Date of Join")) 
            return false;
        if(!sv.isPresent(this.revenueTextField , "Revenue")) 
            return false;
        if(!sv.isDouble(this.revenueTextField , "Revenue")) 
            return false;
        return true;
    }
    private void displayMode(boolean e){
        customerIDTextField.setEditable(!e);
        customerNameTextField.setEditable(!e);
        dateOfJoinTextField.setEditable(!e);
        revenueTextField.setEditable(!e);
        addButton.setEnabled(e);
        updateButton.setEnabled(e);
        deleteButton.setEnabled(e);
    }
    private Customers getCustomer(){
        Customers newCustomer = new Customers();        
        String customerID = customerIDTextField.getText();
        int id = Integer.parseInt(customerID);
        newCustomer.setCustomerID(id);
        String customerName = customerNameTextField.getText();
        newCustomer.setCustomerName(customerName);
        String dateOfJoin = dateOfJoinTextField.getText();
        newCustomer.setDateOfJoin(dateOfJoin);
        String revenue = revenueTextField.getText();
        double rv = Double.parseDouble(revenue);
        newCustomer.setRevenue(rv);
        return newCustomer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerIDTextField = new javax.swing.JTextField();
        customerNameTextField = new javax.swing.JTextField();
        dateOfJoinTextField = new javax.swing.JTextField();
        revenueTextField = new javax.swing.JTextField();
        firstButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        showCustomerListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Management System");

        jLabel1.setText("Customer ID :");

        jLabel2.setText("Customer Name :");

        jLabel3.setText("Date of join :");

        jLabel4.setText("Revenue :");

        firstButton.setText("First");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText("Last");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        showCustomerListButton.setText("Show Customer List");
        showCustomerListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCustomerListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(showCustomerListButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addComponent(firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dateOfJoinTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(customerNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(customerIDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(revenueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acceptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateOfJoinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(revenueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstButton)
                    .addComponent(previousButton)
                    .addComponent(nextButton)
                    .addComponent(lastButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(acceptButton))
                .addGap(18, 18, 18)
                .addComponent(showCustomerListButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        // TODO add your handling code here:
        displayMode(true);
        mode = "";
        this.showCustomer(cDB.getFirstCustomer());
    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        // TODO add your handling code here:
        displayMode(true);
        mode = "";
        this.showCustomer(cDB.getLastCustomer());
    }//GEN-LAST:event_lastButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        displayMode(true);
        mode = "";
        String currentID = customerIDTextField.getText();
        this.showCustomer(cDB.getNextCustomer(currentID));
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        displayMode(true);
        mode = "";
        String currentID = customerIDTextField.getText();
        this.showCustomer(cDB.getPreviousCustomer(currentID));
    }//GEN-LAST:event_previousButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        mode = "add";
        displayMode(false);
        this.clearFields();              
    }//GEN-LAST:event_addButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        if(isValidData()){
            if(mode.equalsIgnoreCase("add")){
                if(cDB.addCustomer(getCustomer())){               
                    JOptionPane.showMessageDialog(acceptButton, "Add successful","Information",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(acceptButton, "Add failed","Information",JOptionPane.INFORMATION_MESSAGE);
                }
            }else if(mode.equalsIgnoreCase("update")){
                if(cDB.updateCustomer(getCustomer(), oldID)){
                    JOptionPane.showMessageDialog(acceptButton, "Update successful","Information",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(acceptButton, "Update failed","Information",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        displayMode(true);
        showCustomer(cDB.getFirstCustomer());
        mode = "";
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        mode = "update";
        String id = customerIDTextField.getText();
        oldID = Integer.parseInt(id);
        displayMode(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String id = customerIDTextField.getText();
        int deleteID = Integer.parseInt(id);
        if(cDB.deleteCustomer(deleteID)){
            JOptionPane.showMessageDialog(acceptButton, "Delete successful","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(acceptButton, "Delete failed","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        displayMode(true);
        mode = "";
        showCustomer(cDB.getFirstCustomer());
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void showCustomerListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCustomerListButtonActionPerformed
        // TODO add your handling code here:
        CustomersList cl = new CustomersList();
        cl.setVisible(true);
    }//GEN-LAST:event_showCustomerListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField customerIDTextField;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField dateOfJoinTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField revenueTextField;
    private javax.swing.JButton showCustomerListButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
